services:
  postgres:
    image: postgres:13
    container_name: ox-barbell-db
    ports:
      - '5432:5432'
    environment:
      - DB_NAME=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: